### ISSUE TITLE
Archivist Integration With GitHub API

### ISSUE THREAD

**Issue by MarcinKosinski** [pbiecek/archivist#110]
Let's have this issue for ideas and rapid development for `Archivist Integration With GitHub API`.

**Comment by MarcinKosinski** [comment]
I have started creating functionalities for `Archivist Integration With GitHub API`. First I have prepared `createEmptyGithubRepo` function which creates new GitHub repository with an empty `archivist`-like `Repository`. The effect of this function is this empty repository https://github.com/MarcinKosinski/Museum-Extra .

I have few doubts and would like to ask you @pbiecek and @wchodor  for advice.

- By now we have `createEmptyRepo` and `createEmptyGithubRepo` functions. This is not consistent. What do you think about creating `createLocalRepo` as a wrapper around `createEmptyRepo` and move `createEmptyRepo` to deprecations? Then change the name of `createEmptyGithubRepo` to `createGithubRepo`? Or maybe we could new names in the wrapper convention `acreate`?
- We have 2 different documentation pages for `createEmptyRepo` and  `createEmptyGithubRepo`. Other sister functions (like loadFromLocalRepo or loadFromGithubRepo) have 1 documentation page. What do you think about having 1 documentation page? Wouldn't it be too long? The `createEmptyGithubRepo` documentation is long because of the configuration explanation. Maybe we should have an extra document page like `GitHub API configuration`?
- What other functions do we need (and what could possible be their best name)? commit_and_pushGithubRepo with `archive` name? I think we only should allow to `push` to repository and not to `pull` (we have `copyRepo` functions).
- Do you have any suggestions or comments?

@wchodor could you kindly check the spelling and linguistic correctness pleas, as you are the expert here :)?

**Comment by wchodor** [comment]
You want me to check linguistic correctness in this comment?

**Comment by MarcinKosinski** [comment]
Sorry, I've just added source code for that function. githubFunctions.R

2015-10-30 10:40 GMT+01:00 Witold Chodor <notifications@github.com>:

**Comment by pbiecek** [comment]
Ad createEmptyRepo. So to be consistent we may add createEmptyLocalRepo (instead of createLocalRepo). But I would still keep createEmptyRepo function with additional argument (e.g. type = c("local", "github")) it will be just a wrapper over createEmptyLocalRepo/createEmptyGitHubRepo. By setting the default type="local" we will not break existing dependencies.

Ad man page, I think that separate 'GitHub API configuration' will be useful. But if it is too large for documentation then let's move it to a vignette. It is actually a nice title for vignette.

Ad commit_and_push. Other option is to have a function like synchroGitHubRepo, that will do pull, commit and push. If different people are working on the same github repository, they may add add artifacts from different computers. But to have consistent 'backpack.db' file we need to pull this file before we can update it.
So maybe we should actually check if others changed the 'bakcpack.db' and pull it if needed before any addToRepo.

**Comment by MarcinKosinski** [comment]
I moved `createEmptyGithubRepo` to the same man page as `createEmptyRepo` and I've added `createEmptyLocalRepo` to maintain consistency with other sister functions. `createEmptyRepo` is now a wrapper around `createEmptyLocalRepo` and `createEmptyGithubRepo`

**Comment by MarcinKosinski** [comment]
@pbiecek I've added `cloneGithubRepo` and  `archive` function which in connection with `createEmptyGithubRepo` automatically created this this repository https://github.com/MarcinKosinski/archive-test and automatically submitted an  artifact with this commit https://github.com/MarcinKosinski/archive-test/commit/66cfe8193a79d32abe65b46e916279962d27cd16

So now, we have 2-way not-so-smart archivist integration with GitHub API for repositories that are used by 1 user at a time.

Do you think instructions in those manual pages``?`archivist-github-integration```, `?createEmptyGithubRepo`, `?cloneGithubRepo` and example in this manual page `?archive`  are sufficient for `pin` function that will integrate `knitr` and `archivist` and `GitHub API` ?

`archive` function has not have completed manual page yet and I think I won't manage to write it before Sunday.

**Comment by MarcinKosinski** [comment]
TODOs:
- We need to extend archive function's documentation
- createEmpyGithubRepo - connect local repo with github after creation

**Comment by MarcinKosinski** [comment]
https://github.com/pbiecek/archivist/commit/96d6bfe6baf746e4452e4b1dbc0a5266ec151ac1

https://github.com/pbiecek/archivist/commit/f8bb5056dab6e15f642f335e43aec8c400ad8a7b

`archive` function has now documentation and `createEmptyGithubRepo` has remote set to `origin`. I think the one-user-integration with GitHub API is done, so far. This issue can be reopened in the future.
