### ISSUE TITLE
[Bug] Can't unset repoDir parameter in aoptions

### ISSUE THREAD

**Issue by MarcinKosinski** [pbiecek/archivist#176]
If one would like to unset the `repoDir` parameter to be `NULL` as it is from the start (when the `archivist` package is loaded), it is impossible because when the second argument of `aoptions` is set to `NULL` then this function returns the argument instead of setting this parameter.

````{R}
> library(archivist)
Welcome to archivist (version: 1.9.3.0).
> aoptions('repoDir')
NULL
> aoptions('repoDir', 'example')
[1] "example"
> aoptions('repoDir')
[1] "example"
> aoptions('repoDir', NULL)
[1] "example"
````

This functionality is crucial to unset `repoDir` when one would like to work with GitHub repo after he set Local repo and is using `aread` function that uses `loadFromRepo` function that checks global parameters. I recommend to add `forceNULL` parameter to the `aoptions` function. This is the cause of  #175

**Comment by MarcinKosinski** [comment]
@pbiecek what do you think about such solution?

**Comment by pbiecek** [comment]
Will be better to find some other solution. Here the forceNULL is only to cover one special case. And NULL is not a real value it's lack of value.

Maybe we can use the value NA?
aoptions('repoDir', NA)
will work as expected and loadFromRepo can be prepared how to deal with NA.

Or use name like unset instead of forceNULL?

The second option is better since the name 'unset' corresponds to the expected behaviour of the function.
