### ISSUE TITLE
session_info in tags

### ISSUE THREAD

**Issue by pbiecek** [pbiecek/archivist#184]
store detailed info about context in which the artifacts was created

**Comment by pbiecek** [comment]
session_info from devtools or sessionInfo from utils?
First is more detailed but then we need to add devtools as dependency

**Comment by MarcinKosinski** [comment]
We can use importFrom devtools aession_info or add this to suggests as we so we shiny in shinySearch. 

Marcin Kosinski

Dnia 27.01.2016 o godz. 22:32 Przemysław Biecek <notifications@github.com> napisał(a):

**Comment by pbiecek** [comment]
ok, good idea
first iteration is in 33ad2bc086e4af663714b910b1f85269396433fc

**Comment by pbiecek** [comment]
updated with c2ee34550bbb6db4cffaaa1c4ec683b699d73ee4

**Comment by MarcinKosinski** [comment]
I've made a few updates, since you were importing `session_info()` from `dplyr` instead of `devtools` and I've added devtools to suggests in DESCRIPTION and in the `.travis.yaml`. I've also added a stop warning when one would try to use new archiveSessionInfo parameter but would not have `devtools` package. Could you maybe provide some tests for this new parameter - then I'll add this new feature to `archive` which works almost the same as `saveToRepo` ?

**Comment by MarcinKosinski** [comment]
And I think, since `devtools` is in `suggests` and we have warning telling that the devtools is needed when it can not be required, then we can remove `devtools` from imports - as we do not import anything from shiny for shinySearch.
