### ISSUE TITLE
A side effect of GithubCheck?

### ISSUE THREAD

**Issue by pbiecek** [pbiecek/archivist#194]
What is happening inside GithubCheck?

Does if call useGithubSetupArguments/useGithubSetupArguments2 for their side effect?
They modify values in parent.frame(2), very risky.

**Comment by pbiecek** [comment]
@MarcinKosinski I think it's a question for you

**Comment by MarcinKosinski** [comment]
They assign the global values of `repo` and `user` in the function's environment. I think this is very old, odd and breakneck. 

It was done on purpose to use global values from `aoptions()` when `NULL` values are passed to `*GithubRepo` function. It can be resolved to be more safe by setting parameters of `*RemoteRepo`/`*GithubRepo` like this

````{R}
loadFromGithubRepo <- function(repo = aoptions('arepo'), user = aoptions('user')
````

instead of 

````{R}
loadFromGithubRepo <- function(repo = NULL, user = NULL)
````

**Comment by pbiecek** [comment]
Ok, so then I will remove GithubCheck and add this default parameters via aoptions()
I think it's safer and more elegant

**Comment by MarcinKosinski** [comment]
Great thanks, indeed it is.
