### ISSUE TITLE
PostgreSQL

### ISSUE THREAD

**Issue by pbiecek** [pbiecek/archivist#313]
An request from email

*Add PostgreSQL backend. SQLite is great, but it doesn’t scale nearly as well as postgres and can’t be hosted on a server. I recognize this is a biggy…*

In my view it's really important, and other issues related with scalability
maybe it's something for summer project for a student

**Comment by eliotmcintire** [comment]
My understanding is you are already using [DBI, which can deal seamlessly with different backends](https://cran.r-project.org/web/packages/DBI/vignettes/backend.html).  So, adding PostgreSQL or other alternatives should be straighforward without too much code change.

In terms of the use case, we are building the [SpaDES](https://CRAN.R-project.org/package=SpaDES) package, which allows for re-useable workflows for various types of problems. As the problems scale, we will be reading and writing potentially large objects (>GBs), and they may potentially be accessed on servers, so many users simultaneously. Since we are starting to run simulations on cloud services (e.g., AWS), it is becoming apparent that we need to have a database backend that can be web accessible, handle multiple concurrent requests, and can handle large data.

SQLite on Linux can *sort of* handle some of these issues that, but it really isn't designed for that use.

**Comment by pbiecek** [comment]
Once the connection to a database is created, everything should works without problem.
The issue that we need to think through are user privileges. 
Shall we have a separate role for superuser to create all required tables and separate role for adding/searching/deleting artifacts. Or just one user. 
Or maybe the connection shall be created without any assistance of archivist package.

**Comment by eliotmcintire** [comment]
I think that archivist just lets the user manage the database priviledges.

So, something where you register the non-SQLite database, so that archivist knows about it.

**Comment by pbiecek** [comment]
@eliotmcintire it took us some time, but there is an experimental solution, maybe you would like to try.
Since after eery transaction we are disconnecting from database, then in the candidate solution we need to have not only a working connection abut rather a connector - function that creates connections.

For example
```
require("RPostgreSQL")
drv <- dbDriver("PostgreSQL")

connector <- function() {
	dbConnect(drv, dbname = "postgres",
                 host = "localhost", port = 5432,
                 user = "user", password = pw)
}
```

with such function one can create an empty repository with `createPostgresRepo()` or access an existing repository with `setPostgresRepo()`.

It's still an experimental solution.
