### ISSUE TITLE
New version goes to CRAN

### ISSUE THREAD

**Issue by pbiecek** [pbiecek/archivist#314]
Maybe we shall upload a new version to CRAN
After solving #310, #313

**Comment by MarcinKosinski** [comment]
I am not sure whether we should have the `.pdf` version https://github.com/pbiecek/archivist/blob/master/vignettes/jss2342.pdf

and `.tex` version of the vignette https://github.com/pbiecek/archivist/blob/master/vignettes/jss2342.tex
when we had the `.Rnw` version.

Were you trying to use the R.rsp package (https://github.com/pbiecek/archivist/blob/master/vignettes/jss2342pdf.asis.tex) - what for, when we have a regular `.Rnw` vignette supported by knitr builder?

**Comment by MarcinKosinski** [comment]
I will try to fix the CRAN CHECK in a sec

**Comment by pbiecek** [comment]
@MarcinKosinski trying different things. The goal is to have
```
vignette(package="archivist")
```
working. Right now
```
> vignette(package="archivist")
no vignettes found
```

**Comment by MarcinKosinski** [comment]
@pbiecek you need to keep pushing me when I do not respond for such a long time. I forgot about this and I am here by accident.

You are probably building a package with `Build and Reload` and not by installing from a created binary file.

The package works and can have vignettes without any changes in the package's structure - you just need to know how to create a package so that it includes vignettes. The second hit from `No vignettes found by browseVignettes` in the google, let me to such [an answer by yihui](https://stackoverflow.com/a/33617870/3857701):

> Note devtools does not build vignettes by default when you devtools::install() (same thing for some install_* functions like install_github()) a package from a directory. You have to specify the argument build_vingettes = TRUE when you install the package. Currently there is no way to build vignettes using devtools if you just use the RStudio button Build & Reload. You have to Build Source Package, and run R CMD INSTALL on the tarball. Or run devtools::install(build_vignettes = TRUE) in the R console.

So after you create a tarball, the vignettes are inside

# screen
<img width="771" alt="screnn" src="https://user-images.githubusercontent.com/6773454/27305212-045259bc-5541-11e7-9469-02b77e7c39de.PNG">




# code

```{R}
> devtools::install(build_vignettes = TRUE)
Installing archivist
"C:/PROGRA~1/R/R-33~1.3/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD build "D:\R  \
  Projects\archivist" --no-resave-data --no-manual 

* checking for file 'D:\R Projects\archivist/DESCRIPTION' ... OK
* preparing 'archivist':
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... OK
* checking for LF line-endings in source and make files
* checking for empty or unneeded directories
Removed empty directory 'archivist/docs'
Removed empty directory 'archivist/man-roxygen'
Removed empty directory 'archivist/vignettes/figure'
* building 'archivist_2.1.3.tar.gz'

"C:/PROGRA~1/R/R-33~1.3/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/kosteck/AppData/Local/Temp/RtmpIdJlAF/archivist_2.1.3.tar.gz"  \
  --library="C:/Users/kosteck/Documents/R/win-library/3.3" --install-tests 

* installing *source* package 'archivist' ...
** R
** demo
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (archivist)
Installing 1 package: devtools
Installing package into ‘C:/Users/kosteck/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/devtools_1.13.2.zip'
Content type 'application/zip' length 439623 bytes (429 KB)
downloaded 429 KB

package ‘devtools’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘devtools’

The downloaded binary packages are in
	C:\Users\kosteck\AppData\Local\Temp\RtmpIdJlAF\downloaded_packages
Installing 1 package: dplyr
Installing package into ‘C:/Users/kosteck/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
Warning: package ‘dplyr’ is in use and will not be installed
Installing 1 package: knitr
Installing package into ‘C:/Users/kosteck/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/knitr_1.16.zip'
Content type 'application/zip' length 1007508 bytes (983 KB)
downloaded 983 KB

package ‘knitr’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\kosteck\AppData\Local\Temp\RtmpIdJlAF\downloaded_packages
Reloading installed archivist
Welcome to archivist (version: 2.1.3).
> browseVignettes('archivist')
```

**Comment by pbiecek** [comment]
@MarcinKosinski you have re-opened this issue. Why? Is it ready to be closed?

**Comment by MarcinKosinski** [comment]
@pbiecek Perhaps I wanted you to respond to the comment. But no idea now. Vignettes are seen in the tar.gz but not in the build by devtools option so that development is faster when you don't build vignettes every time.

Vignettes should be visible on CRAN, the moment you create a binary and provide the upload. Then if one installs package from CRAN, he'll see vignettes. Moreover building from GitHub sometimes results the way you don't see vignettes also.
