### ISSUE TITLE
Archiving artifacts with their chaining code

### ISSUE THREAD

**Issue by MarcinKosinski** [pbiecek/archivist#63]
Maybe should we copy functionality of the pipe `%>%` operator from the previous version of `magrittr` package to able to archive artifacts with their chaining code?

**Comment by pbiecek** [comment]
Risky, 
If we use same name, i.e. %>% then people will suffer from name collisions (same operator %>% different functionalities depending on order of package loading)
If we use other name, e.g. %.% then people will not know about it and will not use it 

Ok, we can give them some reasons to use it.

So maybe we can use different name (like %a%) and extended functionality? More like the planned for integration with Lukasz’s defer package?

**Comment by MarcinKosinski** [comment]
%a% looks good :)

**Comment by MarcinKosinski** [comment]
Ok this operator was added and use case can be seen here :)
http://pbiecek.github.io/archivist/chainingUseCase.html

**Comment by pbiecek** [comment]
It turns out that I was thinking about different functionality, so let's discuss this operator.
The added value of %a% might be that it stores information both about the LHS and the result but also about the call itself.
So in fact there will be no need for adding saveToRepo() after the chaining code
it will be done inside.

For example
iris %a% ggplot(.,aes(x=Sepal.Length, y=Petal.Length))

Will call saveToRepo for iris,
Then for resulting output,
Then for the operation itself.

So when tracing sources of the resulting object, then the user will know that it was produced from iris with the use of ‘iris %a% ggplot(.,aes(x=Sepal.Length, y=Petal.Length))’ expression

Proposition:
1. use %a% as the %>% and add new operator for the functionality described above
2. use %.% or %>% as a copy of original %>% and change %a% to a new operator as described above

what do you think?
