### ISSUE TITLE
formats of artifacts in the repository - rdx/rdb backend [extras to rda format]

### ISSUE THREAD

**Issue by MarcinKosinski** [pbiecek/archivist#90]
By now with this commit: f4e72a8
it is possible to specify format in which artifacts can be stored in the `gallery` directory of the repository.
The example is below

````{R}
> library(archivist)
Welcome to archivist (version: 1.8.1).
> deleteRepo("format_test")
> createEmptyRepo("format_test", default = TRUE)
> 
> saveToRepo(iris)
[1] "ff575c261c949d073b2895b05d1097c3"
> library(datasets)
> data(iris3)
> saveToRepo(iris3, format = "rdb")
[1] "40beeb27e7bb0b84d415d6bdc06f4a62"
> data(longley)
> aoptions("format", "rdb")
[1] "rdb"
> saveToRepo(longley)
[1] "a9c4ea5c0ad4a8493e726e1e4223aa18"
> 
> showLocalRepo()
                           md5hash    name         createdDate
1 ff575c261c949d073b2895b05d1097c3    iris 2015-09-30 19:26:08
2 40beeb27e7bb0b84d415d6bdc06f4a62   iris3 2015-09-30 19:26:08
3 a9c4ea5c0ad4a8493e726e1e4223aa18 longley 2015-09-30 19:26:08
> list.files("format_test/gallery/")
[1] "40beeb27e7bb0b84d415d6bdc06f4a62.rdb"
[2] "a9c4ea5c0ad4a8493e726e1e4223aa18.rdb"
[3] "a9c4ea5c0ad4a8493e726e1e4223aa18.txt"
[4] "ff575c261c949d073b2895b05d1097c3.rda"
[5] "ff575c261c949d073b2895b05d1097c3.txt"
````

One would have to think about creating a function/or editing an existing one to load such objects that are not stored in a regular default format `rda`. Probably it would be a good idea to add a tag  to an object that would clarify in which format the artifact was archived.

What do you think about that?

**Comment by eliotmcintire** [comment]
Looking at the code for saveToRepo, this looks like only a file extension change, not a format change. The `save` function only will produce `rda` formats. To save an object in an `rdb`/`rdx` lazy load database, it requires `getFromNamespace(x = "makeLazyLoadDB", "tools")`. For saving an object in other formats, say `.txt`, it requires other functions also, say `write.table` or `write.csv`.

**Comment by MarcinKosinski** [comment]
Thanks for hint. I'll fix that as soon as possible :) 

Marcin Kosinski

Dnia 2 paź 2015 o godz. 18:48 Eliot McIntire <notifications@github.com> napisał(a):

**Comment by MarcinKosinski** [comment]
Ok, can you check if this works now for you? It somehow looks like to work for me on the simplest example.

````{R}
> library(archivist)
> createEmptyRepo("DSA")
Directory DSA did not exist. Forced to create a new directory.
> setLocalRepo("DSA")
> saveToRepo(iris, format = "rdx")
[1] "ff575c261c949d073b2895b05d1097c3"
> list.files("DSA/gallery/")
[1] "5d3eb62caa2d99b343b74717e883a372.rdb" "ff575c261c949d073b2895b05d1097c3.rdb"
[3] "ff575c261c949d073b2895b05d1097c3.rdx" "ff575c261c949d073b2895b05d1097c3.txt"
````

How do you plan to load those objects (saved in that new format)?

**Comment by eliotmcintire** [comment]
Lazy objects get loaded with `lazyLoad` in the base package.  This will, like `load`, load objects into the calling environment with the object name that it had going into the lazy load database. (This is unlike `saveRDS` behaviour which doesn't have an object name associated and therefore requires an assignment operator upon `readRDS`.)  Having said this, your new code doesn't keep that information (i.e,. the object name), so using `lazyLoad( )` is not working correctly. The object needs to have an object name so that the `lazyLoad()` will work. See line 433 in https://github.com/PredictiveEcology/lazyR/blob/master/R/lazyR.R for the lazyLoad function use.

What is the .txt representation for?

There is some strange behaviour within the saveToRepo2 function. It is requiring a list or environment, which is true for data.frames and such, but not vectors, matrices, or any other arbitrary object. Notably, it seems like the checks around lines 426-436 are getting the wrong behaviour for data.frames as each column is getting dealt with separately. Maybe that is what you want. ?

**Comment by MarcinKosinski** [comment]
@eliotmcintire  .`txt` representation is for artifact's miniature. You can check explanation of the archiveMiniature parameter in the `saveToRepo` function

> archiveMiniature	
A logical value denoting whether to archive a miniature of the artifact

Talkig about:

> There is some strange behaviour within the saveToRepo2 function. It is requiring a list or environment, which is true for data.frames and such, but not vectors, matrices, or any other arbitrary object. Notably, it seems like the checks around lines 426-436 are getting the wrong behaviour for data.frames as each column is getting dealt with separately. Maybe that is what you want. ?

I've just copied the function `getFromNamespace(x = "makeLazyLoadDB", "tools")` as you suggested. I've got no idea how does it work :) Can you say if the save in `.rdx` format is correct? Or it doesn't work for `vectors`?

**Comment by eliotmcintire** [comment]
`makeLazyLoadDB` is exactly equivalent to `save`, except instead of an `.rda` file format, it is an `.rdx/.rdb` pair. The rdx is an index file, which gives some index of the contents of the `.rdb` file so that the `.rdb` file doesn't have to be loaded into RAM until needed. The `.rdb` file, I believe, is exactly the same format as the `.rda` format. So, any arbitrary object can be put in an `.rdb` file. The only difference in using `.rdx/.rdb` files is that when you load them back, you don't use `load()` you use `lazyLoad()`. 

So, whatever your functions are for saving and loading `.rda` files should be exactly the same for saving and loading `.rdx/.rdb` files.

See: https://stat.ethz.ch/R-manual/R-devel/library/base/html/lazyload.html

**Comment by MarcinKosinski** [comment]
So why we do need those .rdb/.rdx files when we have metadata about objects
stored in the `backpack.db`? We don't need to load any object from
repository, we can check it's contents before loading by looking at its
tags/metadata that are stored in `backpack.db`? One can specify his own
tags while saving an artifact by using `userTags` in  `saveToRepo`
function. I am loosing a point of using those .rdb/.rdx extensions.

I understood that metadata are stored in a separete files which is, in my
opinion, a bad solution. One might want to explore metadata of various
objects at the same time. One backpack.db file storing all metadata is a
convinient solution for that.

2015-10-27 23:12 GMT+01:00 Eliot McIntire <notifications@github.com>:

**Comment by eliotmcintire** [comment]
Note: the makeLazyLoadDB may not be able to be put into a package that will be submitted to CRAN. It is a non-exported function. So, if you don't want to work more on this, for strategic or other reasons, it is possible to let the [lazyR](https://github.com/PredictiveEcology/lazyR/) package do the lazy load database stuff, with archivist as the backend. It is likely that the [lazyR](https://github.com/PredictiveEcology/lazyR/) package won't be uploaded to CRAN because of this, until the makeLazyLoadDB function is exported

The only request at that point would be to give a little more control over putting objects into the archivist repository. At the moment, within the [lazyR](https://github.com/PredictiveEcology/lazyR/),  package, the `.rda` file gets created using the `saveToRepo` function, but it is just a dummy file with nothing in it. So, the `gallery` folder has 3 files for every object, an `.rda`, and `.rdx` and an `.rdb`.

**Comment by eliotmcintire** [comment]
The advantage of having them in lazyLoad databases, for us, is that we can use the objects as native R objects, and we don't have to use a separate structure to look at them. In other words, we can say `ls()` and we will get the list of the objects, we can use any R function natively, and the objects load seamlessly. If we have to use the `archivist` functions to access them, then it means there is programming overhead in an interactive environment.  You have to think about loading objects before using them. With the lazyLoad approach, you can load a lot of objects into an environment, and not necessarily use them all. There may be a sequence of 15 objects that get created that are all cached (via the %a% or just with 15 object assignments or `archivist::cache` calls) for example. Then the 15th object is used for something else. All 15 steps may create large objects, so fitting them all into RAM is not an option. The first time the code gets run, they can all be created (and perhaps removed with `rm()` along the way). The second time, they are "reloaded" into the environment from the cached versions, but there isn't enough RAM to hold them all. If they are lazy objects, then only the final object actually uses any RAM, once it is used. Each object is only a promise, not actually the object.

As you say, there are some excellent uses for the SQLite database as the indexing tool. But it doesn't quite cover all the use cases that we are interested in.

**Comment by MarcinKosinski** [comment]
Yes, .rda files might be a dummy file, that's why we are extending the
metada system by tag creation. Archivist was created to work in a way in
which one first explore metadata repository (backpack.db) and then collect
objects that are in interest. If one has problems with RAM the na amazon
ec2 tool might be used (+300gb RAM for 3$ for an hour of computations). I
think the management of objects that do not fit to the RAM on a regular
machine is not so complicated if one uses save/saveToRepo/rm  and then
explore analysis results by using tags. It might be more inconvenient to
think about loading a file before it should be loaded but it might be safer
to think about it. I can imagine a situation that I
unintentionally load to many objects while letting load be done without of
the control.

So far I would not like to add dependencies to the packages that are not on
CRAN and moreover I don't understand if you are proposing me to add
dependencies to lazyR which is already dependent on archivist?

Do you need to add any functionalities to the archivist::saveToRepo
function?

Besides, what is the problem with making
makeLazyLoadDB to be an exported function?

2015-10-28 0:56 GMT+01:00 Eliot McIntire <notifications@github.com>:

**Comment by eliotmcintire** [comment]
I was not proposing making lazyR a dependency. It is, as you say, the other way around. I was proposing that if the functionality of lazy load objects is not interesting for you and it creates too many problems, including the issue that CRAN does not allow unexpected functions to be used in a package (if you try using tools:::makeLazyLoadDB, then run R CMD check, youyou get a warning... You don't get the warning if you call it with getFromNamespace, but I think that may be an oversight. There have been many discussions online about exporting that function and all have been met with "No" ), then you can leave it out of your package. Then if other people want to use lazy load objects, they can get the lazyR package, and by inheritance, the archivist package. I am fine if you continue working on getting lazyLoad databases into archivist, but it sounded like you are convinced it isn't necessary.

**Comment by MarcinKosinski** [comment]
Updates performed after CRAN CHECK. 
Format parameter in `saveToRepo` removed as it does not pass CRAN CHECK.
